import java.util.Optional;


class User2{
    private String name;
    public User2(String name){
        this.name = name;
    }

    public String getName(){
        return name;
    }
}
public class Java_Optional {
    public static void main(String[] args) {

  // 1. Creating Optional
        Optional<String> opt1 = Optional.empty();                 // empty optional
        Optional<String> opt2 = Optional.of("Ashu");              // value must NOT be null
        Optional<String> opt3 = Optional.ofNullable(null);        // can be null or non-null


        // 2. Checking value present or not
        System.out.println(opt1.isPresent());   // false
        System.out.println(opt2.isPresent());   // true
        System.out.println(opt2.isEmpty());     // false
        System.out.println(opt1.isEmpty());     // true


        // 3. Getting value
        System.out.println(opt2.get());          // Ashu
        // opt1.get();  // throws NoSuchElementException (DON'T use get() blindly)


        // 4. orElse() → return default if value is missing
        String name1 = opt2.orElse("Default Name");
        String name2 = opt1.orElse("Default Name");
        System.out.println(name1);               // Ashu
        System.out.println(name2);               // Default Name


        // 5. orElseGet() → lazy version of orElse() (uses Supplier)
        String lazy = opt1.orElseGet(() -> "Generated by Supplier");
        System.out.println(lazy);


        // 6. orElseThrow() → throw exception if empty
        try {
            opt1.orElseThrow(() -> new RuntimeException("Value missing"));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }


        // 7. ifPresent() → run code if value exists
        opt2.ifPresent(value -> System.out.println("Value: " + value));


        // 8. ifPresentOrElse()
        opt1.ifPresentOrElse(
                val -> System.out.println("Found: " + val),
                () -> System.out.println("Not Found")
        );


        // 9. map() → transform value inside Optional
        Optional<String> upper = opt2.map(String::toUpperCase);
        System.out.println(upper.orElse("No data"));


        // 10. flatMap() → return Optional from mapping
        Optional<Optional<String>> nested = Optional.of(Optional.of("Hello"));
        Optional<String> flat = nested.flatMap(value -> value);
        System.out.println(flat.get());  // Hello


        // 11. filter() → apply condition
        Optional<String> filtered = opt2.filter(val -> val.startsWith("A"));
        System.out.println(filtered.orElse("Doesn't match"));


        // 12. Chaining Optionals (realistic example)
        Optional<String> result =
                Optional.ofNullable("Ashu")
                        .filter(val -> val.length() > 2)
                        .map(String::toUpperCase); //String::toUpperCase = val -> val.toUpperCase()


        System.out.println(result.orElse("Invalid"));
    }
}
